---
- hosts: web

  tasks:
  - name: delete old containers
    command: docker-compose down -f docker-compose.yml -d

  - name: create container
    command: docker-compose -f docker-compose.yml up -d
